name: æ¯æ—¥ 'w' ã‚’ã‚³ãƒŸãƒƒãƒˆ

on:
  schedule:
    - cron: '0 10 * * *'
  
  # GitHubã®Actionsã‚¿ãƒ–ã‹ã‚‰æ‰‹å‹•ã§å®Ÿè¡Œã§ãã‚‹ã‚ˆã†ã«ã™ã‚‹
  workflow_dispatch:

jobs:
  commit_w:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: ãƒªãƒã‚¸ãƒˆãƒªã‚’ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
        uses: actions/checkout@v4

      - name: 'w.txt' ã« 'w' ã‚’è¿½è¨˜
        run: echo "w" >> w.txt

      - name: å¤‰æ›´ã‚’ã‚³ãƒŸãƒƒãƒˆ & ãƒ—ãƒƒã‚·ãƒ¥
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated commit: Add 'w' ğŸŒ¿"
          file_pattern: w.txt # ã‚³ãƒŸãƒƒãƒˆå¯¾è±¡ã®ãƒ•ã‚¡ã‚¤ãƒ«ã‚’æŒ‡å®š
          commit_user_name: github-actions[bot] # ãƒœãƒƒãƒˆåã‚’æŒ‡å®š
          commit_user_email: github-actions[bot]@users.noreply.github.com # ãƒœãƒƒãƒˆã®Emailã‚’æŒ‡å®š